phonon: disable vlc backend
Does not build anymore. On walnascar, I get the following
error:

ERROR: Nothing PROVIDES 'vlc' (but /home/marc/mnt/build/plasma-demo/../../yocto-kde-demo/meta-plasma-demo/repos/meta-kf6/recipes-kdesupport/phonon-backend-vlc_0.12.0.bb DEPENDS on or otherwise requires it)
vlc was skipped: Recipe will be skipped because: requires porting to ffmpeg >= 7 as of ffmpeg >= 5 it requires extensive changes disabling VAAPI (only supported with vlc >= 4)

Comment out the RRECOMMENDS line and add a comment so we leave a
trace. Maybe someone else will tackle this issue in the future.

Signed-off-by: Marc Ferland <marc.ferland@sonatest.com>